export const API_ERRORED = "API_ERRORED";
export const DATA_LOADED = "DATA_LOADED";
export const DATA_REQUESTED = "DATA_REQUESTED";
export const INVALID_SYMBOL_CHARACTERS = "INVALID_SYMBOL_CHARACTERS";
export const INVALID_SYMBOL_LENGTH = "INVALID_SYMBOL_LENGTH";